# Jekyll workshop-template-b evanwill
# https://github.com/evanwill/workshop-template-b

# Notes: 
# - pages with "nav: true" in front matter will be in header nav
# - figure include for centered images, put file in images directory and use: {% include figure.html img="my-cat.jpg" alt="cat" caption="My cat" width="50%" %}

# Site settings
# title appears in the header
title: workshop-template-b
# description and keywords for meta tags
description: "Create a workshop website quick and easy!"
keywords: "workshops, websites, gh-pages, jekyll"

# author settings for cc-by, appears in the footer
author: evan will
pub_year: 2018
github_username: evanwill
twitter_username: EvanPeterWill

# add the full url for the github repository
repo: "https://github.com/evanwill/workshop-template-b"

# site urls
# add the url for the domain,
# on gh-pages follow the pattern: https://username.github.io 
url: https://evanwill.github.io
# add subsection of the domain,
# on gh-pages this is a / followed by the name of the repository
baseurl: /workshop-template-b

# add search box to footer?
search: true

# add google analytics if desired (optional)
# if blank, it will be ignored
# use JEKYLL_ENV=production on build command
google_analytics: 

# defaults (to simplify front matter)
defaults:
  - scope:
      path: "content"
    values:
      layout: "default"
# Build settings
markdown: kramdown
